#!/usr/bin/env python3
"""Draw the Postmark Trips postcards into art/ as flat SVG landscapes (city, coast, desert, mountain, island, lake).
Every picture is generated by this script, so it is free to reuse and shows no real place or person."""
import json, math, os, random
HERE = os.path.dirname(os.path.abspath(__file__)); OUT = os.path.join(HERE, "art"); os.makedirs(OUT, exist_ok=True)
PALS = {"dawn": ["#ffd9b8", "#f7a072", "#e0705a", "#2f5d9e", "#1d2a44"], "noon": ["#cfe7f2", "#8cc4de", "#e9b44c", "#2f7d6d", "#1d2a44"],
        "dusk": ["#f6c6a8", "#d97b66", "#8f4b6b", "#3d3f6e", "#1d2a44"], "desert": ["#f8e3c4", "#f2b880", "#d9734e", "#9c4a3c", "#3b2a2a"],
        "teal": ["#d8efe8", "#9fd3c7", "#e9b44c", "#2a7f8f", "#183a47"], "rose": ["#fbe2dc", "#f4a7a0", "#d64545", "#3f6e8c", "#1d2a44"]}

def ridge(y, amp, n, w, h, col, r, op=1):
    pts, x = [], 0
    while x <= w + 40:
        pts.append(f"L{x},{y - r.uniform(0, amp):.0f}"); x += w / n
    return f'<path d="M0,{h} {" ".join(pts)} L{w},{h} Z" fill="{col}" opacity="{op}"/>'

def waves(y, w, h, col, r, op=1):
    d = f"M0,{y}" + "".join(f" q{w/16:.0f},{-8 - r.random()*4:.0f} {w/8:.0f},0" for _ in range(9))
    return f'<path d="{d} L{w},{h} L0,{h} Z" fill="{col}" opacity="{op}"/>'

def card(name, scene, pal, seed, w=1200, h=900):
    r = random.Random(seed); p = PALS[pal]; sky1, sky2, acc, mid, ink = p
    s = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" width="{w}" height="{h}"><defs>'
         f'<linearGradient id="sky" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="{sky2}"/><stop offset="1" stop-color="{sky1}"/></linearGradient>'
         '<filter id="g"><feTurbulence type="fractalNoise" baseFrequency=".9" numOctaves="2" stitchTiles="stitch"/><feColorMatrix values="0 0 0 0 .4 0 0 0 0 .35 0 0 0 0 .3 0 0 0 .35 0"/></filter></defs>',
         f'<rect width="{w}" height="{h}" fill="url(#sky)"/>']
    sx, sy = r.uniform(.2, .8) * w, r.uniform(.18, .34) * h
    s.append(f'<circle cx="{sx:.0f}" cy="{sy:.0f}" r="{r.uniform(60, 95):.0f}" fill="{acc}" opacity=".95"/>')
    for _ in range(3):  # clouds
        cx, cy = r.uniform(0, w), r.uniform(.08, .3) * h
        s.append(f'<g fill="#fff" opacity=".7"><ellipse cx="{cx:.0f}" cy="{cy:.0f}" rx="90" ry="22"/><ellipse cx="{cx+40:.0f}" cy="{cy-14:.0f}" rx="50" ry="22"/></g>')
    if scene in ("mountain", "lake"):
        s.append(ridge(h * .45, 160, 7, w, h, mid, r, .55)); s.append(ridge(h * .58, 140, 9, w, h, ink, r, .75))
        if scene == "lake":
            s.append(f'<rect y="{h*.68:.0f}" width="{w}" height="{h*.32:.0f}" fill="{sky2}"/>')
            for i in range(8): s.append(f'<rect x="{r.uniform(0,w):.0f}" y="{h*.7+i*28:.0f}" width="{r.uniform(80,260):.0f}" height="4" rx="2" fill="#fff" opacity=".5"/>')
        else:
            s.append(ridge(h * .78, 60, 14, w, h, mid, r))
            for _ in range(26):
                tx, ty = r.uniform(0, w), r.uniform(.8, .95) * h
                s.append(f'<path d="M{tx:.0f},{ty-46:.0f} l18,46 h-36 z" fill="{ink}" opacity=".85"/>')
    elif scene in ("coast", "island"):
        if scene == "island":
            s.append(f'<ellipse cx="{w*.55:.0f}" cy="{h*.62:.0f}" rx="{w*.28:.0f}" ry="{h*.12:.0f}" fill="{mid}"/>')
            s.append(ridge(h * .6, 120, 5, w, h, ink, r, 0) )
            s.append(f'<path d="M{w*.4:.0f},{h*.6:.0f} Q{w*.55:.0f},{h*.32:.0f} {w*.7:.0f},{h*.6:.0f} Z" fill="{ink}" opacity=".8"/>')
        else:
            s.append(f'<path d="M0,{h*.42:.0f} C{w*.2:.0f},{h*.38:.0f} {w*.35:.0f},{h*.55:.0f} {w*.5:.0f},{h*.62:.0f} L0,{h*.7:.0f} Z" fill="{ink}" opacity=".85"/>')
            for i in range(9):  # little houses on the cliff
                hx, hy = 30 + i * 52, h * .44 + i * 18
                s.append(f'<rect x="{hx:.0f}" y="{hy:.0f}" width="40" height="34" fill="{["#fff",acc,sky1][i%3]}"/><path d="M{hx-4:.0f},{hy:.0f} l24,-16 l24,16 z" fill="{["#d64545",mid][i%2]}"/>')
        for i in range(5): s.append(waves(h * (.64 + i * .07), w, h, [mid, sky2, mid, "#fff", mid][i], r, [.9, .6, .8, .25, 1][i]))
    elif scene == "desert":
        s.append(ridge(h * .62, 40, 3, w, h, mid, r, .45))
        s.append(f'<path d="M{w*.15:.0f},{h*.68:.0f} h{w*.12:.0f} v-{h*.16:.0f} h-{w*.12:.0f} z" fill="{mid}"/><path d="M{w*.6:.0f},{h*.68:.0f} l60,-{h*.22:.0f} l60,{h*.22:.0f} z" fill="{ink}" opacity=".6"/>')
        s.append(f'<path d="M0,{h*.7:.0f} C{w*.3:.0f},{h*.62:.0f} {w*.6:.0f},{h*.78:.0f} {w},{h*.68:.0f} L{w},{h} L0,{h} Z" fill="{acc}"/>')
        s.append(f'<path d="M0,{h*.82:.0f} C{w*.4:.0f},{h*.74:.0f} {w*.7:.0f},{h*.9:.0f} {w},{h*.8:.0f} L{w},{h} L0,{h} Z" fill="{mid}" opacity=".85"/>')
        for _ in range(4):
            cx = r.uniform(.1, .9) * w; cy = h * .9
            s.append(f'<g fill="{ink}"><rect x="{cx-9:.0f}" y="{cy-110:.0f}" width="18" height="110" rx="9"/><rect x="{cx-38:.0f}" y="{cy-80:.0f}" width="14" height="44" rx="7"/><rect x="{cx-38:.0f}" y="{cy-44:.0f}" width="36" height="12" rx="6"/></g>')
    else:  # city
        s.append(ridge(h * .55, 80, 6, w, h, mid, r, .35))
        x = 0
        while x < w:
            bw, bh = r.uniform(50, 120), r.uniform(.18, .42) * h
            s.append(f'<rect x="{x:.0f}" y="{h*.78-bh:.0f}" width="{bw:.0f}" height="{bh+h*.3:.0f}" fill="{r.choice([mid, ink, sky1, acc])}" opacity=".95"/>')
            if r.random() < .3: s.append(f'<path d="M{x:.0f},{h*.78-bh:.0f} l{bw/2:.0f},-{bw*.6:.0f} l{bw/2:.0f},{bw*.6:.0f} z" fill="#d64545"/>')
            for wy in range(int(h * .78 - bh + 20), int(h * .78), 34):
                for wx in range(int(x + 10), int(x + bw - 14), 22): s.append(f'<rect x="{wx}" y="{wy}" width="9" height="14" fill="#fff" opacity=".45"/>')
            x += bw + r.uniform(2, 10)
        s.append(waves(h * .8, w, h, sky2, r, .9)); s.append(waves(h * .86, w, h, mid, r))
    s.append(f'<rect width="{w}" height="{h}" filter="url(#g)" opacity=".5"/></svg>')
    open(os.path.join(OUT, name + ".svg"), "w").write("".join(s))

spec = json.load(open(os.path.join(HERE, "art.json")))
for i, (n, scene, pal) in enumerate(spec): card(n, scene, pal, i * 7 + 3)
print("wrote", len(spec), "postcards to", OUT)
